import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/common/header";
import ScrollToTopButton from "@/components/common/scroll-to-top-button";
import SocialContainer from "@/components/common/social-container";
import Footer from "@/components/common/footer";
import { getHeaderData } from "@/lib/queries/getHeaderData";
import { getFooterData } from "@/lib/queries/getFooterData";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headerData = await getHeaderData();
  const footerData = await getFooterData();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen`}
      >
        <Header data={headerData} />
        {children}
        {/* <Footer data={footerData} /> */}
        {/* <ScrollToTopButton /> */}
        {/* <SocialContainer /> */}
      </body>
    </html>
  );
}
